#!/bin/bash

dep ensure -v
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o admission-webhook-example 
docker build --no-cache -t ${DOCKER_USER}/webhook:v1 .
rm -rf admission-webhook-example
docker push ${DOCKER_USER}/webhook:v1
